services:
  - type: web
    name: fastapi-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false   
      - key: GEMINI_API_KEY
        sync: false   
      - key: LLM_TIMEOUT_SECONDS
        value: 240
